/**
 * otp-v0.10 Phase 2 · Supabase-first OTP records: the Google Sheet MIRROR.
 *
 * From otp-v0.10 the OTP form writes its record to Supabase FIRST (edge function
 * otp-submit -> otp_write, migrate_19_otp_writes.sql) and gets its answer in about
 * a second. The edge function then POSTs the finished record here
 * ({ form:'otp', action:'mirror', record, pending_since }) and this file makes the
 * Sheet row EQUAL to that record, as given: no id or token is ever regenerated
 * (a second token would break every teacher viewer link), the same emails go out
 * as before (sendOtpSubmissionEmail / sendOtpTeacherEmail on a new row,
 * sendOtpCloseEmail when a lap closes), and the record is marked mirrored in
 * Supabase (mark_otp_mirrored). The Sheet keeps every row; it may lag, never lose.
 *
 *   handleOtpMirror(data)      doPost route for action:'mirror' (idempotent: an
 *                              existing token is updated, never appended twice)
 *   healOtpMirror()            the 5-minute trigger + doPost action:'heal': mirrors
 *                              every record otp_unmirrored() still lists (older
 *                              than 2 min, still unmirrored), e.g. after this
 *                              endpoint was slow or down when the edge function called
 *   installOtpHealTrigger()    run ONCE from the editor: installs the 5-minute trigger
 *
 * The live otp-v0.9.4 form never sends action:'mirror' or 'heal', so its path
 * (handleOtpPost / handleOtpUpdateOrClose) is unchanged by this file. Hard rule 12
 * holds: every email and every Supabase call sits in its own try/catch.
 */

const OTP_MIRROR_RPC_UNMIRRORED = '/rest/v1/rpc/otp_unmirrored';
const OTP_MIRROR_RPC_MARK       = '/rest/v1/rpc/mark_otp_mirrored';
const OTP_MIRROR_RPC_STAMP      = '/rest/v1/rpc/stamp_otp_emailed';
const OTP_MIRROR_RPC_RECORD     = '/rest/v1/rpc/otp_record_for_mirror';
const OTP_HEAL_TRIGGER_HANDLER  = 'healOtpMirror';
const OTP_HEAL_OLDER_THAN_S     = 120;
const OTP_HEAL_BATCH            = 5;     // per run: each record can cost a Sheet write + emails

/** A record_token as generated by generateRecordToken() / otp_write(): 32 lowercase hex chars. */
function otpTokenOk_(t) {
  return /^[0-9a-f]{32}$/.test(String(t || '').trim());
}

/**
 * The OTP tab with its header row present and healed to getOtpColumns(), the
 * same rule handleOtpPost applied inline until otp-v0.10 (existing rows keep
 * their positions; only trailing header cells are ever written).
 */
function getOtpSheetWithHeader_(ss) {
  let sheet = ss.getSheetByName(SHEET_NAME_OTP_SUBMISSIONS);
  if (!sheet) sheet = ss.insertSheet(SHEET_NAME_OTP_SUBMISSIONS);
  const columns = getOtpColumns();
  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, columns.length).setValues([columns]);
    sheet.setFrozenRows(1);
    sheet.getRange(1, 1, 1, columns.length)
         .setFontWeight('bold')
         .setBackground('#143642')
         .setFontColor('#ffffff');
    sheet.setColumnWidths(1, columns.length, 140);
  } else if (sheet.getLastColumn() < columns.length) {
    const from = sheet.getLastColumn();
    sheet.getRange(1, from + 1, 1, columns.length - from)
         .setValues([columns.slice(from)])
         .setFontWeight('bold')
         .setBackground('#143642')
         .setFontColor('#ffffff');
  }
  return sheet;
}

/** { values, headers, rowIdx } for the row whose record_token equals `token` (rowIdx -1 = none). */
function findOtpRowByToken_(sheet, token) {
  const want = String(token || '').trim();
  if (!want || sheet.getLastRow() < 2) return { values: null, headers: null, rowIdx: -1 };
  const values = sheet.getDataRange().getValues();
  const headers = values[0];
  const tokenCol = headers.indexOf('record_token');
  var rowIdx = -1;
  if (tokenCol > -1) {
    for (var r = 1; r < values.length; r++) {
      if (String(values[r][tokenCol] || '').trim() === want) { rowIdx = r; break; }
    }
  }
  return { values: values, headers: headers, rowIdx: rowIdx };
}

/** One Sheet cell from the record: missing -> '', objects -> JSON text, else as given. */
function otpCellValue_(record, header) {
  const v = record[header];
  if (v == null) return '';
  if (typeof v === 'object') return JSON.stringify(v);
  return v;
}

/**
 * Makes the Sheet row for `record` (the full record as Supabase holds it, keyed
 * by column name) equal to the record. Idempotent by record_token: a missing
 * row is appended and the submit emails go out; an existing row is overwritten
 * in place and the close email goes out only when the row CHANGES to closed.
 * Returns { appended, updated, closedNow }.
 */
function mirrorOtpRecord_(ss, sheet, record, opts) {
  opts = opts || {};
  const token = String(record.record_token || '').trim();
  const found = findOtpRowByToken_(sheet, token);
  // Only the contract columns are written; a column someone appended by hand
  // beyond getOtpColumns() is never touched.
  const headers = getOtpColumns();
  const out = { appended: false, updated: false, closedNow: false, skipped: false };
  const isClosed = String(record.status || '').trim() === 'closed';
  const rowValues = headers.map(function(h) { return otpCellValue_(record, h); });

  if (found.rowIdx < 0) {
    sheet.appendRow(rowValues);
    out.appended = true;
    var submissionMail = { sent: false, coachIncluded: false };
    var coachStamp = '';
    try {
      submissionMail = sendOtpSubmissionEmail(ss, record.record_id, token, record.submitted_at, record);
      if (submissionMail && submissionMail.sent && submissionMail.coachIncluded) coachStamp = new Date().toISOString();
    } catch (mailErr) {
      Logger.log('OTP mirror: submission email failed for ' + record.record_id + ': ' + mailErr.message);
    }
    var teacherMail = false;
    var teacherStamp = '';
    try {
      teacherMail = sendOtpTeacherEmail(ss, record.record_id, token, record.submitted_at, record);
      if (teacherMail) teacherStamp = new Date().toISOString();
    } catch (mailErr) {
      Logger.log('OTP mirror: teacher email failed for ' + record.record_id + ': ' + mailErr.message);
    }
    try {
      const stampStart = headers.indexOf('coach_emailed_at') + 1;
      if (stampStart > 0) {
        sheet.getRange(sheet.getLastRow(), stampStart, 1, 2).setValues([[
          coachStamp || otpCellValue_(record, 'coach_emailed_at'),
          teacherStamp || otpCellValue_(record, 'teacher_emailed_at')
        ]]);
      }
    } catch (stampErr) {
      Logger.log('OTP mirror: Sheet email stamp failed for ' + record.record_id + ': ' + stampErr.message);
    }
    try {
      stampOtpEmailed_(token, coachStamp, teacherStamp);
    } catch (stampErr) {
      Logger.log('OTP mirror: Supabase email stamp failed for ' + record.record_id + ': ' + stampErr.message);
    }
    if (isClosed) out.closedNow = true;   // submitted and closed before its first mirror landed
  } else {
    const liveStatusCol = found.headers.indexOf('status');
    const wasClosed = liveStatusCol > -1 && String(found.values[found.rowIdx][liveStatusCol] || '').trim() === 'closed';
    if (wasClosed && !isClosed) {
      // A closed lap is final on the Sheet exactly as it is in Supabase
      // (otp_write refuses to reopen one). Whatever handed us an open record
      // for a closed row is stale: leave the row alone.
      Logger.log('OTP mirror: refused to reopen closed row ' + record.record_id);
      out.skipped = true;
      return out;
    }
    ['coach_emailed_at', 'teacher_emailed_at'].forEach(function(stamp) {
      const col = headers.indexOf(stamp);
      const liveCol = found.headers.indexOf(stamp);
      if (col > -1 && liveCol > -1 && String(found.values[found.rowIdx][liveCol] || '').trim() && !String(rowValues[col] || '').trim()) {
        rowValues[col] = found.values[found.rowIdx][liveCol];
      }
    });
    sheet.getRange(found.rowIdx + 1, 1, 1, headers.length).setValues([rowValues]);
    out.updated = true;
    if (!wasClosed && isClosed) out.closedNow = true;
  }

  if (out.closedNow) {
    try {
      sendOtpCloseEmail(ss, record);
    } catch (mailErr) {
      Logger.log('OTP mirror: close email failed for ' + record.record_id + ': ' + mailErr.message);
    }
    // Same as handleOtpUpdateOrClose: the next observation of this teacher must
    // see the just-closed lap now, not after the 60 s cache. The pre-warm read
    // is slow (8-83 s uncached), so the heal sweep skips it (opts.prewarm false).
    try {
      clearPrevNextStepsCache(record.teacher);
      if (opts.prewarm !== false) getOtpPrevNextSteps(record.teacher);
    } catch (e) {}
  }
  return out;
}

/**
 * Supabase's CURRENT state of one OTP record (otp_record_for_mirror, service
 * key): { found, record, pending_since, mirrored_at }. The mirror always copies
 * THIS, never the payload it was handed, so two mirrors arriving out of order
 * both write the latest state and the anonymous route can only trigger a copy.
 */
function fetchOtpRecordForMirror_(token) {
  const secret = getSupabaseSecret();
  if (!secret) throw new Error('SUPABASE_SECRET_KEY not set');
  const resp = UrlFetchApp.fetch(SUPABASE_URL + OTP_MIRROR_RPC_RECORD, {
    method: 'post',
    contentType: 'application/json',
    headers: { 'apikey': secret, 'Authorization': 'Bearer ' + secret },
    payload: JSON.stringify({ p_token: token }),
    muteHttpExceptions: true
  });
  if (resp.getResponseCode() !== 200) throw new Error('otp_record_for_mirror HTTP ' + resp.getResponseCode());
  const out = JSON.parse(resp.getContentText());
  return out && out.found ? out : null;
}

/**
 * Mirrors one token from Supabase's current state into the Sheet and marks it,
 * under the script lock (one Sheet writer at a time; handleOtpPost and
 * handleOtpUpdateOrClose take the same lock). Returns the mirror result plus
 * `marked`, or null when Supabase has no such record.
 */
function mirrorOtpTokenFromSupabase_(ss, sheet, token, opts) {
  const cur = fetchOtpRecordForMirror_(token);
  if (!cur || !cur.record) return null;
  const lock = LockService.getScriptLock();
  lock.waitLock(30000);
  var out;
  try {
    out = mirrorOtpRecord_(ss, sheet, cur.record, opts);
  } finally {
    lock.releaseLock();
  }
  out.marked = false;
  if (!out.skipped) {
    try {
      out.marked = markOtpMirrored_(token, cur.pending_since);
    } catch (e) {
      Logger.log('OTP mirror: mark failed for ' + token + ': ' + e.message);
    }
  }
  out.id = cur.record.record_id;
  return out;
}

/** mark_otp_mirrored in Supabase (service key). True when a row was marked. */
function markOtpMirrored_(token, pendingSince) {
  const secret = getSupabaseSecret();
  if (!secret) { Logger.log('OTP mirror: SUPABASE_SECRET_KEY not set, cannot mark'); return false; }
  const resp = UrlFetchApp.fetch(SUPABASE_URL + OTP_MIRROR_RPC_MARK, {
    method: 'post',
    contentType: 'application/json',
    headers: { 'apikey': secret, 'Authorization': 'Bearer ' + secret },
    payload: JSON.stringify({ p_token: token, p_pending_since: pendingSince || null }),
    muteHttpExceptions: true
  });
  if (resp.getResponseCode() !== 200) {
    Logger.log('OTP mirror: mark_otp_mirrored HTTP ' + resp.getResponseCode() + ': ' + resp.getContentText());
    return false;
  }
  var out = {};
  try { out = JSON.parse(resp.getContentText()); } catch (e) {}
  return !!(out && out.success && out.marked > 0);
}

/** Stamp successful OTP email recipients without changing mirror state. */
function stampOtpEmailed_(token, coachAt, teacherAt) {
  const secret = getSupabaseSecret();
  if (!secret) { Logger.log('OTP mirror: SUPABASE_SECRET_KEY not set, cannot stamp email'); return false; }
  try {
    const resp = UrlFetchApp.fetch(SUPABASE_URL + OTP_MIRROR_RPC_STAMP, {
      method: 'post',
      contentType: 'application/json',
      headers: { 'apikey': secret, 'Authorization': 'Bearer ' + secret },
      payload: JSON.stringify({ p_token: token, p_coach_at: coachAt || null, p_teacher_at: teacherAt || null }),
      muteHttpExceptions: true
    });
    if (resp.getResponseCode() !== 200) {
      Logger.log('OTP mirror: stamp_otp_emailed HTTP ' + resp.getResponseCode() + ': ' + resp.getContentText());
      return false;
    }
    const out = JSON.parse(resp.getContentText());
    if (!out || Number(out.stamped) === 0) {
      Logger.log('OTP mirror: stamp_otp_emailed miss for ' + token);
      return false;
    }
    return true;
  } catch (e) {
    Logger.log('OTP mirror: stamp_otp_emailed failed for ' + token + ': ' + e.message);
    return false;
  }
}

/** doPost route for { form:'otp', action:'mirror', record, pending_since }. */
function handleOtpMirror(data) {
  // The payload's record is ignored on purpose: only its token is used, and
  // the copy comes from Supabase's current state (see fetchOtpRecordForMirror_).
  const token = String((data && data.record_token) || (data && data.record && data.record.record_token) || '').trim();
  if (!otpTokenOk_(token)) return jsonOut({ success: false, error: 'bad record' });
  const ss = SpreadsheetApp.openById(getSheetId());
  const sheet = getOtpSheetWithHeader_(ss);
  const out = mirrorOtpTokenFromSupabase_(ss, sheet, token, { prewarm: true });
  if (!out) return jsonOut({ success: false, error: 'Record not found' });
  return jsonOut({ success: true, id: out.id, appended: out.appended, updated: out.updated, closed: out.closedNow, skipped: out.skipped, marked: out.marked });
}

/**
 * The heal sweep: every OTP record Supabase still lists as unmirrored after
 * OTP_HEAL_OLDER_THAN_S seconds is mirrored now. Runs from the 5-minute trigger
 * and from doPost action:'heal'. Returns a summary object (also logged).
 */
function healOtpMirror() {
  const secret = getSupabaseSecret();
  if (!secret) return { success: false, error: 'SUPABASE_SECRET_KEY not set' };
  const resp = UrlFetchApp.fetch(SUPABASE_URL + OTP_MIRROR_RPC_UNMIRRORED, {
    method: 'post',
    contentType: 'application/json',
    headers: { 'apikey': secret, 'Authorization': 'Bearer ' + secret },
    payload: JSON.stringify({ p_older_than_seconds: OTP_HEAL_OLDER_THAN_S }),
    muteHttpExceptions: true
  });
  if (resp.getResponseCode() !== 200) {
    Logger.log('OTP heal: otp_unmirrored HTTP ' + resp.getResponseCode() + ': ' + resp.getContentText());
    return { success: false, error: 'otp_unmirrored HTTP ' + resp.getResponseCode() };
  }
  var items = [];
  try { items = JSON.parse(resp.getContentText()) || []; } catch (e) {}
  if (!items.length) return { success: true, pending: 0, healed: 0, failed: 0 };

  const ss = SpreadsheetApp.openById(getSheetId());
  const sheet = getOtpSheetWithHeader_(ss);
  // A few per run, each under its own short lock and without the slow
  // previous-lap pre-warm, so a long backlog never runs into the 6-minute
  // execution limit while holding the Sheet; the next run takes the rest.
  const batch = items.slice(0, OTP_HEAL_BATCH);
  var healed = 0, failed = 0;
  batch.forEach(function(it) {
    const token = String((it && it.record && it.record.record_token) || '').trim();
    if (!otpTokenOk_(token)) { failed++; return; }
    try {
      const out = mirrorOtpTokenFromSupabase_(ss, sheet, token, { prewarm: false });
      if (out && out.marked) healed++; else failed++;
    } catch (e) {
      failed++;
      Logger.log('OTP heal: ' + token + ' failed: ' + e.message);
    }
  });
  const summary = { success: true, pending: items.length, healed: healed, failed: failed };
  Logger.log('OTP heal: ' + JSON.stringify(summary));
  return summary;
}

/** Installs the 5-minute heal trigger once (removes any duplicate first). */
function installOtpHealTrigger() {
  ScriptApp.getProjectTriggers().forEach(function(t) {
    if (t.getHandlerFunction() === OTP_HEAL_TRIGGER_HANDLER) ScriptApp.deleteTrigger(t);
  });
  ScriptApp.newTrigger(OTP_HEAL_TRIGGER_HANDLER)
    .timeBased()
    .everyMinutes(5)
    .create();
  return 'installed: ' + OTP_HEAL_TRIGGER_HANDLER + ' every 5 minutes';
}
