/**
 * otp-v0.10 Phase 2 · Supabase-first OTP records: the Google Sheet MIRROR.
 *
 * From otp-v0.10 the OTP form writes its record to Supabase FIRST (edge function
 * otp-submit -> otp_write, migrate_19_otp_writes.sql) and gets its answer in about
 * a second. The edge function then POSTs the finished record here
 * ({ form:'otp', action:'mirror', record, pending_since }) and this file makes the
 * Sheet row EQUAL to that record, as given: no id or token is ever regenerated
 * (a second token would break every teacher viewer link), the same emails go out
 * as before (sendOtpSubmissionEmail / sendOtpTeacherEmail on a new row,
 * sendOtpCloseEmail when a lap closes), and the record is marked mirrored in
 * Supabase (mark_otp_mirrored). The Sheet keeps every row; it may lag, never lose.
 *
 *   handleOtpMirror(data)      doPost route for action:'mirror' (idempotent: an
 *                              existing token is updated, never appended twice)
 *   healOtpMirror()            the 5-minute trigger + doPost action:'heal': mirrors
 *                              every record otp_unmirrored() still lists (older
 *                              than 2 min, still unmirrored), e.g. after this
 *                              endpoint was slow or down when the edge function called
 *   installOtpHealTrigger()    run ONCE from the editor: installs the 5-minute trigger
 *
 * The live otp-v0.9.4 form never sends action:'mirror' or 'heal', so its path
 * (handleOtpPost / handleOtpUpdateOrClose) is unchanged by this file. Hard rule 12
 * holds: every email and every Supabase call sits in its own try/catch.
 */

const OTP_MIRROR_RPC_UNMIRRORED = '/rest/v1/rpc/otp_unmirrored';
const OTP_MIRROR_RPC_MARK       = '/rest/v1/rpc/mark_otp_mirrored';
const OTP_HEAL_TRIGGER_HANDLER  = 'healOtpMirror';
const OTP_HEAL_OLDER_THAN_S     = 120;

/** A record_token as generated by generateRecordToken() / otp_write(): 32 lowercase hex chars. */
function otpTokenOk_(t) {
  return /^[0-9a-f]{32}$/.test(String(t || '').trim());
}

/**
 * The OTP tab with its header row present and healed to getOtpColumns(), the
 * same rule handleOtpPost applied inline until otp-v0.10 (existing rows keep
 * their positions; only trailing header cells are ever written).
 */
function getOtpSheetWithHeader_(ss) {
  let sheet = ss.getSheetByName(SHEET_NAME_OTP_SUBMISSIONS);
  if (!sheet) sheet = ss.insertSheet(SHEET_NAME_OTP_SUBMISSIONS);
  const columns = getOtpColumns();
  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, columns.length).setValues([columns]);
    sheet.setFrozenRows(1);
    sheet.getRange(1, 1, 1, columns.length)
         .setFontWeight('bold')
         .setBackground('#143642')
         .setFontColor('#ffffff');
    sheet.setColumnWidths(1, columns.length, 140);
  } else if (sheet.getLastColumn() < columns.length) {
    const from = sheet.getLastColumn();
    sheet.getRange(1, from + 1, 1, columns.length - from)
         .setValues([columns.slice(from)])
         .setFontWeight('bold')
         .setBackground('#143642')
         .setFontColor('#ffffff');
  }
  return sheet;
}

/** { values, headers, rowIdx } for the row whose record_token equals `token` (rowIdx -1 = none). */
function findOtpRowByToken_(sheet, token) {
  const want = String(token || '').trim();
  if (!want || sheet.getLastRow() < 2) return { values: null, headers: null, rowIdx: -1 };
  const values = sheet.getDataRange().getValues();
  const headers = values[0];
  const tokenCol = headers.indexOf('record_token');
  var rowIdx = -1;
  if (tokenCol > -1) {
    for (var r = 1; r < values.length; r++) {
      if (String(values[r][tokenCol] || '').trim() === want) { rowIdx = r; break; }
    }
  }
  return { values: values, headers: headers, rowIdx: rowIdx };
}

/** One Sheet cell from the record: missing -> '', objects -> JSON text, else as given. */
function otpCellValue_(record, header) {
  const v = record[header];
  if (v == null) return '';
  if (typeof v === 'object') return JSON.stringify(v);
  return v;
}

/**
 * Makes the Sheet row for `record` (the full record as Supabase holds it, keyed
 * by column name) equal to the record. Idempotent by record_token: a missing
 * row is appended and the submit emails go out; an existing row is overwritten
 * in place and the close email goes out only when the row CHANGES to closed.
 * Returns { appended, updated, closedNow }.
 */
function mirrorOtpRecord_(ss, sheet, record) {
  const token = String(record.record_token || '').trim();
  const found = findOtpRowByToken_(sheet, token);
  const headers = found.headers || getOtpColumns();
  const out = { appended: false, updated: false, closedNow: false };
  const isClosed = String(record.status || '').trim() === 'closed';
  const rowValues = headers.map(function(h) { return otpCellValue_(record, h); });

  if (found.rowIdx < 0) {
    sheet.appendRow(rowValues);
    out.appended = true;
    try {
      sendOtpSubmissionEmail(ss, record.record_id, token, record.submitted_at, record);
    } catch (mailErr) {
      Logger.log('OTP mirror: submission email failed for ' + record.record_id + ': ' + mailErr.message);
    }
    try {
      sendOtpTeacherEmail(ss, record.record_id, token, record.submitted_at, record);
    } catch (mailErr) {
      Logger.log('OTP mirror: teacher email failed for ' + record.record_id + ': ' + mailErr.message);
    }
    if (isClosed) out.closedNow = true;   // submitted and closed before its first mirror landed
  } else {
    const statusCol = headers.indexOf('status');
    const wasClosed = statusCol > -1 && String(found.values[found.rowIdx][statusCol] || '').trim() === 'closed';
    sheet.getRange(found.rowIdx + 1, 1, 1, headers.length).setValues([rowValues]);
    out.updated = true;
    if (!wasClosed && isClosed) out.closedNow = true;
  }

  if (out.closedNow) {
    try {
      sendOtpCloseEmail(ss, record);
    } catch (mailErr) {
      Logger.log('OTP mirror: close email failed for ' + record.record_id + ': ' + mailErr.message);
    }
    // Same as handleOtpUpdateOrClose: the next observation of this teacher must
    // see the just-closed lap now, not after the 60 s cache, and the uncached
    // read is slow, so pre-warm it while the Sheet is open.
    try {
      clearPrevNextStepsCache(record.teacher);
      getOtpPrevNextSteps(record.teacher);
    } catch (e) {}
  }
  return out;
}

/** mark_otp_mirrored in Supabase (service key). True when a row was marked. */
function markOtpMirrored_(token, pendingSince) {
  const secret = getSupabaseSecret();
  if (!secret) { Logger.log('OTP mirror: SUPABASE_SECRET_KEY not set, cannot mark'); return false; }
  const resp = UrlFetchApp.fetch(SUPABASE_URL + OTP_MIRROR_RPC_MARK, {
    method: 'post',
    contentType: 'application/json',
    headers: { 'apikey': secret, 'Authorization': 'Bearer ' + secret },
    payload: JSON.stringify({ p_token: token, p_pending_since: pendingSince || null }),
    muteHttpExceptions: true
  });
  if (resp.getResponseCode() !== 200) {
    Logger.log('OTP mirror: mark_otp_mirrored HTTP ' + resp.getResponseCode() + ': ' + resp.getContentText());
    return false;
  }
  var out = {};
  try { out = JSON.parse(resp.getContentText()); } catch (e) {}
  return !!(out && out.success && out.marked > 0);
}

/** doPost route for { form:'otp', action:'mirror', record, pending_since }. */
function handleOtpMirror(data) {
  const record = data && data.record;
  if (!record || !otpTokenOk_(record.record_token) || !String(record.record_id || '').trim()) {
    return jsonOut({ success: false, error: 'bad record' });
  }
  const ss = SpreadsheetApp.openById(getSheetId());
  const sheet = getOtpSheetWithHeader_(ss);
  // One mirror at a time: the edge function and the heal sweep may both hold
  // this record, and two appends of one token would be the duplicate this
  // whole path exists to prevent.
  const lock = LockService.getScriptLock();
  lock.waitLock(30000);
  var out;
  try {
    out = mirrorOtpRecord_(ss, sheet, record);
  } finally {
    lock.releaseLock();
  }
  var marked = false;
  try {
    marked = markOtpMirrored_(String(record.record_token).trim(), data.pending_since);
  } catch (e) {
    Logger.log('OTP mirror: mark failed for ' + record.record_id + ': ' + e.message);
  }
  return jsonOut({ success: true, id: record.record_id, appended: out.appended, updated: out.updated, closed: out.closedNow, marked: marked });
}

/**
 * The heal sweep: every OTP record Supabase still lists as unmirrored after
 * OTP_HEAL_OLDER_THAN_S seconds is mirrored now. Runs from the 5-minute trigger
 * and from doPost action:'heal'. Returns a summary object (also logged).
 */
function healOtpMirror() {
  const secret = getSupabaseSecret();
  if (!secret) return { success: false, error: 'SUPABASE_SECRET_KEY not set' };
  const resp = UrlFetchApp.fetch(SUPABASE_URL + OTP_MIRROR_RPC_UNMIRRORED, {
    method: 'post',
    contentType: 'application/json',
    headers: { 'apikey': secret, 'Authorization': 'Bearer ' + secret },
    payload: JSON.stringify({ p_older_than_seconds: OTP_HEAL_OLDER_THAN_S }),
    muteHttpExceptions: true
  });
  if (resp.getResponseCode() !== 200) {
    Logger.log('OTP heal: otp_unmirrored HTTP ' + resp.getResponseCode() + ': ' + resp.getContentText());
    return { success: false, error: 'otp_unmirrored HTTP ' + resp.getResponseCode() };
  }
  var items = [];
  try { items = JSON.parse(resp.getContentText()) || []; } catch (e) {}
  if (!items.length) return { success: true, pending: 0, healed: 0, failed: 0 };

  const ss = SpreadsheetApp.openById(getSheetId());
  const sheet = getOtpSheetWithHeader_(ss);
  const lock = LockService.getScriptLock();
  lock.waitLock(30000);
  var healed = 0, failed = 0;
  try {
    items.forEach(function(it) {
      const rec = it && it.record;
      if (!rec || !otpTokenOk_(rec.record_token)) { failed++; return; }
      try {
        mirrorOtpRecord_(ss, sheet, rec);
        if (markOtpMirrored_(String(rec.record_token).trim(), it.pending_since)) healed++; else failed++;
      } catch (e) {
        failed++;
        Logger.log('OTP heal: ' + rec.record_id + ' failed: ' + e.message);
      }
    });
  } finally {
    lock.releaseLock();
  }
  const summary = { success: true, pending: items.length, healed: healed, failed: failed };
  Logger.log('OTP heal: ' + JSON.stringify(summary));
  return summary;
}

/** Installs the 5-minute heal trigger once (removes any duplicate first). */
function installOtpHealTrigger() {
  ScriptApp.getProjectTriggers().forEach(function(t) {
    if (t.getHandlerFunction() === OTP_HEAL_TRIGGER_HANDLER) ScriptApp.deleteTrigger(t);
  });
  ScriptApp.newTrigger(OTP_HEAL_TRIGGER_HANDLER)
    .timeBased()
    .everyMinutes(5)
    .create();
  return 'installed: ' + OTP_HEAL_TRIGGER_HANDLER + ' every 5 minutes';
}
