// Assemble template/composition.html from template/skeleton.html + template/fragments/.
// Markers: <!-- @@SECTION:<sceneid>@@ -->  and  /* @@CUES:<sceneid>@@ */
// Also concatenates fragments/<sceneid>.css into styles/scenes.css.
// Idempotent: always regenerates from the pristine skeleton. Run before build.mjs.
import fs from 'node:fs';
import path from 'node:path';
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const FRAG = path.join(ROOT, 'template', 'fragments');
let html = fs.readFileSync(path.join(ROOT, 'template', 'skeleton.html'), 'utf8');
let css = '/* GENERATED by scripts/assemble.mjs from template/fragments/<scene>.css. Do not hand-edit. */\n';
const missing = [];
for (const m of [...html.matchAll(/<!-- @@SECTION:([a-z0-9_]+)@@ -->/g)].map(x => x[1])) {
  const f = path.join(FRAG, m + '.section.html');
  if (fs.existsSync(f)) html = html.replace(`<!-- @@SECTION:${m}@@ -->`, fs.readFileSync(f, 'utf8').trim());
  else missing.push(m + '.section.html');
}
for (const m of [...html.matchAll(/\/\* @@CUES:([a-z0-9_]+)@@ \*\//g)].map(x => x[1])) {
  const f = path.join(FRAG, m + '.cues.js');
  if (fs.existsSync(f)) html = html.replace(`/* @@CUES:${m}@@ */`, fs.readFileSync(f, 'utf8').trim());
  else missing.push(m + '.cues.js');
}
for (const f of fs.readdirSync(FRAG).filter(f => f.endsWith('.css')).sort()) {
  css += `\n/* ---- ${f} ---- */\n` + fs.readFileSync(path.join(FRAG, f), 'utf8');
}
fs.writeFileSync(path.join(ROOT, 'template', 'composition.html'), html);
fs.writeFileSync(path.join(ROOT, 'styles', 'scenes.css'), css);
console.log('assembled template/composition.html + styles/scenes.css' + (missing.length ? `\nMISSING: ${missing.join(', ')}` : ' (all fragments present)'));
